#!/bin/bash -e

. ./script/concerns/loader

if command -v ollama &>/dev/null; then
  start_loader "Upgrading ollama"
  ./script/concerns/linux/upgrade-ollama &>>./log/upgrade.log
  stop_loader

  start_loader "Pulling models. This may take a while..."
  ./script/concerns/pull-models &>>./log/upgrade.log
  stop_loader
fi

start_loader "Upgrading Nosia"
# Pull latest changes
git pull &>>./log/upgrade.log
# Build Nosia
docker compose --env-file .env build &>>./log/upgrade.log
stop_loader
