#!/bin/bash

. ./script/concerns/loader

if brew list ollama &>/dev/null; then
  start_loader "Starting ollama"
  OLLAMA_MAX_LOADED_MODELS=3 ollama serve &>./log/ollama.log &
  stop_loader
fi

start_loader "Starting Nosia"
podman machine start &>./log/podman.log
podman-compose --env-file .env up -d &>./log/podman.log
stop_loader
