#!/bin/bash

. ./script/concerns/loader

start_loader "Stopping Nosia"
podman-compose down &> ./log/podman.log
podman machine stop &> ./log/podman.log
stop_loader

start_loader "Stopping ollama"
killall "ollama" &> ./log/ollama.log
stop_loader
