#!/bin/bash

. ./script/concerns/loader

start_loader "Stopping Nosia"
podman-compose down &>> ./log/podman.log
podman machine stop
stop_loader

start_loader "Stopping ollama"
killall "ollama" &>> ./log/ollama.log
stop_loader
