#!/bin/bash -e

sudo apt install postgresql-16 postgresql-16-pgvector libpq-dev
sudo -u postgres psql -c "SELECT 1 FROM pg_roles WHERE rolname='$USER'" | grep -q 1 || sudo -u postgres createuser $USER -s
