#!/bin/bash -e

if command -v ollama &> /dev/null; then
  echo "ollama is already installed"
  exit 0
fi

if [ -z "$OLLAMA_URL" ]; then
  echo "OLLAMA_URL is already set"
  exit 0
fi

curl -fsSL https://ollama.com/install.sh | sh
OLLAMA_NUM_PARALLEL=3 OLLAMA_MAX_LOADED_MODELS=2 ollama serve
