#!/bin/bash -e

if [ "$OLLAMA_URL" != "http://localhost:11434" ]; then
  echo "OLLAMA_URL is not localhost"
  exit 0
fi

if command -v ollama &> /dev/null; then
  echo "ollama is already installed"
  exit 0
fi

curl -fsSL https://ollama.com/install.sh | sh
OLLAMA_MAX_LOADED_MODELS=3 ollama serve
