#!/bin/bash -e

if [ "$OLLAMA_URL" != "http://localhost:11434" ]; then
  echo "OLLAMA_URL is not localhost"
  exit 0
fi

source ./script/concerns/loader

start_loader "Starting Ollama"
sudo systemctl start ollama.service &>> ./log/production.log
stop_loader
