#!/usr/bin/env bash

play_loader_loop() {
  local animation=(| / - \)

  while true; do
    for frame in "${animation[@]}"; do
      printf "\r%s" "${frame}"
      sleep 0.25
    done
  done
}

start_loader() {
  MESSAGE="${1}"
  echo -n "   ${MESSAGE}"
  tput civis # Hide the terminal cursor
  play_loader_loop &
  loader_pid="${!}"
}

stop_loader() {
  printf "\r[x]"
  kill "${loader_pid}" &>/dev/null
  printf "\n"
  tput cnorm # Restore the terminal cursor
}

exit_loader() {
  printf "\r   ${MESSAGE}\n"
  kill "${loader_pid}" &>/dev/null
  tput cnorm # Restore the terminal cursor
}

kill_loader() {
  kill "${loader_pid}" &>/dev/null
  tput cnorm # Restore the terminal cursor
}

trap kill_loader SIGINT
trap kill_loader SIGKILL
trap kill_loader SIGTERM
