#!/bin/bash -e

if [ -f .env ]; then
  echo ".env file already exists"
  exit 0
fi

echo "Generating .env file"

if [ -n "$NOSIA_URL" ]; then
  echo "Using NOSIA_URL from environment"
else
  echo "NOSIA_URL is not set, using default value"
  NOSIA_URL=https://nosia.localhost
fi

if [ -n "$OLLAMA_URL" ]; then
  echo "Using OLLAMA_URL from environment"
else
  echo "OLLAMA_URL is not set, using default value"
  OLLAMA_URL=http://localhost:11434
fi

if [ -n "$OLLAMA_CHAT_COMPLETION_MODEL" ]; then
  echo "Using OLLAMA_CHAT_COMPLETION_MODEL from environment"
else
  echo "OLLAMA_CHAT_COMPLETION_MODEL is not set, using default value"
  OLLAMA_CHAT_COMPLETION_MODEL=phi3:medium
fi

if [ -n "$OLLAMA_COMPLETION_MODEL" ]; then
  echo "Using OLLAMA_COMPLETION_MODEL from environment"
else
  echo "OLLAMA_COMPLETION_MODEL is not set, using default value"
  OLLAMA_COMPLETION_MODEL=phi3:medium
fi

if [ -n "$OLLAMA_EMBEDDINGS_MODEL" ]; then
  echo "Using OLLAMA_EMBEDDINGS_MODEL from environment"
else
  echo "OLLAMA_EMBEDDINGS_MODEL is not set, using default value"
  OLLAMA_EMBEDDINGS_MODEL=nomic-embed-text
fi

POSTGRES_HOST=postgres-db
POSTGRES_PORT=5432
POSTGRES_DB=nosia_production
POSTGRES_USER=nosia
POSTGRES_PASSWORD=$(openssl rand -hex 32)
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
SECRET_KEY_BASE=$(openssl rand -hex 64)

echo "DATABASE_URL=$DATABASE_URL" > .env
echo "NOSIA_URL=$NOSIA_URL" >> .env
echo "OLLAMA_URL=$OLLAMA_URL" >> .env
echo "OLLAMA_CHAT_COMPLETION_MODEL=$OLLAMA_CHAT_COMPLETION_MODEL" >> .env
echo "OLLAMA_COMPLETION_MODEL=$OLLAMA_COMPLETION_MODEL" >> .env
echo "OLLAMA_EMBEDDINGS_MODEL=$OLLAMA_EMBEDDINGS_MODEL" >> .env
echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
echo "POSTGRES_DB=$POSTGRES_DB" >> .env
echo "POSTGRES_USER=$POSTGRES_USER" >> .env
echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
echo "SECRET_KEY_BASE=$SECRET_KEY_BASE" >> .env

echo ".env file generated"
