#!/bin/bash -e

if [ -f .env ]; then
  echo ".env file already exists"
  exit 0
fi

echo "Generating .env file"

if [ -n "$NOSIA_URL" ]; then
  echo "Using NOSIA_URL from environment"
else
  echo "NOSIA_URL is not set, using default value"
  NOSIA_URL=https://nosia.localhost
fi

if [ -n "$OLLAMA_BASE_URL" ]; then
  echo "Using OLLAMA_BASE_URL from environment"
else
  echo "OLLAMA_BASE_URL is not set, using default value"
  OLLAMA_BASE_URL=http://localhost:11434
fi

if [ -n "$LLM_MODEL" ]; then
  echo "Using LLM_MODEL from environment"
else
  echo "LLM_MODEL is not set, using default value"
  LLM_MODEL=mistral-small3.2
fi

if [ -n "$CHECK_MODEL" ]; then
  echo "Using CHECK_MODEL from environment"
else
  echo "CHECK_MODEL is not set, using default value"
  CHECK_MODEL=bespoke-minicheck
fi

if [ -n "$EMBEDDING_MODEL" ]; then
  echo "Using EMBEDDING_MODEL from environment"
else
  echo "EMBEDDING_MODEL is not set, using default value"
  EMBEDDING_MODEL=nomic-embed-text
fi

POSTGRES_HOST=postgres-db
POSTGRES_PORT=5432
POSTGRES_DB=nosia_production
POSTGRES_USER=nosia
POSTGRES_PASSWORD=$(openssl rand -hex 32)
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
SECRET_KEY_BASE=$(openssl rand -hex 64)

echo "DATABASE_URL=$DATABASE_URL" >.env
echo "NOSIA_URL=$NOSIA_URL" >>.env
echo "OLLAMA_BASE_URL=$OLLAMA_BASE_URL" >>.env
echo "OLLAMA_API_KEY=" >>.env
echo "LLM_MODEL=$LLM_MODEL" >>.env
echo "CHECK_MODEL=$CHECK_MODEL" >>.env
echo "EMBEDDING_MODEL=$EMBEDDING_MODEL" >>.env
echo "SMTP_ADDRESS=" >>.env
echo "SMTP_PORT=" >>.env
echo "SMTP_USER_NAME=" >>.env
echo "SMTP_PASSWORD=" >>.env
echo "POSTGRES_HOST=$POSTGRES_HOST" >>.env
echo "POSTGRES_PORT=$POSTGRES_PORT" >>.env
echo "POSTGRES_DB=$POSTGRES_DB" >>.env
echo "POSTGRES_USER=$POSTGRES_USER" >>.env
echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >>.env
echo "SECRET_KEY_BASE=$SECRET_KEY_BASE" >>.env
echo "LLM_TEMPERATURE=0.1" >>.env
echo "CHUNK_SIZE=1000" >>.env
echo "CHUNK_OVERLAP=200" >>.env
echo 'SEPARATORS=["\n\n", "\n", " "]' >>.env
echo "LLM_NUM_CTX=8_192" >>.env
echo "LLM_TOP_K=40" >>.env
echo "LLM_TOP_P=0.9" >>.env
echo "RETRIEVAL_FETCH_K=3" >>.env
echo 'RAG_SYSTEM_TEMPLATE="You are Nosia, a helpful assistant. If necessary, use the information contained in the Nosia helpful content. Give a comprehensive answer to the question. Respond only to the question asked, response should be relevant to the question. If the answer cannot be deduced from the Nosia helpful content, do not use the context."' >>.env

cat >>.env <<EOF
QUERY_PROMPT_TEMPLATE="Nosia helpful content:
{context}

---

Now here is the question you need to answer.

Question: {question}"
EOF

echo ".env file generated"
