#!/bin/bash -e

source ./script/concerns/loader

start_loader "Setting up environment"
OLLAMA_CHAT_COMPLETION_MODEL=$OLLAMA_CHAT_COMPLETION_MODEL OLLAMA_COMPLETION_MODEL=$OLLAMA_COMPLETION_MODEL OLLAMA_URL=$OLLAMA_URL ./script/production/setup-env &>> ./log/production.log
stop_loader

start_loader "Setting up Docker"
./script/production/setup-docker &>> ./log/production.log
stop_loader

start_loader "Setting up Ollama"
./script/ollama/setup &>> ./log/production.log
stop_loader
