#!/bin/bash -e

if [ -f .env ]; then
  echo ".env file already exists"
  exit 0
fi

echo "Generating .env file"

if [ -n "$RAILS_MASTER_KEY" ]; then
  echo "Using RAILS_MASTER_KEY from environment"
else
  echo "RAILS_MASTER_KEY is not set, exiting"
  exit 1
fi
if [ -n "$OLLAMA_URL" ]; then
  echo "Using OLLAMA_URL from environment"
else
  echo "OLLAMA_URL is not set, using default value"
  OLLAMA_URL=http://localhost:11434
fi
OLLAMA_MODEL=phi3:medium
POSTGRES_HOST=postgres-db
POSTGRES_PORT=5432
POSTGRES_DB=nosia_production
POSTGRES_USER=nosia
POSTGRES_PASSWORD=$(openssl rand -base64 32)
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB

echo "DATABASE_URL=$DATABASE_URL" > .env
echo "OLLAMA_URL=$OLLAMA_URL" >> .env
echo "OLLAMA_MODEL=$OLLAMA_MODEL" >> .env
echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
echo "POSTGRES_DB=$POSTGRES_DB" >> .env
echo "POSTGRES_USER=$POSTGRES_USER" >> .env
echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
echo "RAILS_MASTER_KEY=$RAILS_MASTER_KEY" >> .env

echo ".env file generated"
