#!/bin/bash -e

. ./script/concerns/loader

if [ "$OLLAMA_URL" == "http://localhost:11434" ]; then
  ./script/ollama/start
fi

start_loader "Starting Nosia"
trap exit_loader EXIT
newgrp docker <<EONG
docker compose --env-file .env up -d &>> ./log/production.log
EONG
stop_loader
