#!/bin/bash -e

source ./script/concerns/loader

if [ "$OLLAMA_URL" == "http://localhost:11434" ]; then
  ./script/ollama/start
fi

start_loader "Starting Nosia"
source .env
trap exit_loader EXIT
docker compose up -d &>> ./log/production.log
stop_loader
