#!/bin/bash -e

source ./script/concerns/loader

start_loader "Stopping Ollama"
sudo systemctl stop ollama.service &>> ./log/production.log
stop_loader

start_loader "Stopping Nosia"
docker compose down &>> ./log/production.log
stop_loader
