#!/bin/bash -e

source ./script/concerns/loader

if [ "$OLLAMA_URL" == "http://localhost:11434" ]; then
  ./script/ollama/stop
fi

start_loader "Stopping Nosia"
docker compose down &>> ./log/production.log
stop_loader
