#!/bin/bash -e

source ./script/concerns/loader

./script/ollama/upgrade &>> ./log/production.log

start_loader "Pulling latest changes of Nosia"
git pull &>> ./log/production.log
stop_loader

start_loader "Upgrading Nosia"
source .env
trap exit_loader EXIT
docker compose down &>> ./log/production.log
docker compose build &>> ./log/production.log
docker compose up -d &>> ./log/production.log
stop_loader
