#!/bin/bash -e

. ./script/concerns/loader

./script/ollama/upgrade &>> ./log/production.log

start_loader "Pulling latest changes of Nosia"
git pull &>> ./log/production.log
stop_loader

start_loader "Upgrading Nosia"
trap exit_loader EXIT
newgrp docker <<EONG
docker compose down &>> ./log/production.log
docker compose build &>> ./log/production.log
docker compose --env-file .env up -d --force-recreate &>> ./log/production.log
EONG
stop_loader
